services:
  qlines_app_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: test_image

    container_name: test_container5
    #command: gunicorn -w 4 -b 0.0.0.0:5000 qlines:app --chdir /opt/qlines_app
    #privileged: true
    #restart: unless-stopped
    ports:
    #  - "7000-7100:7000-7100" # for mqtt and dbs
    #- "80:5000"  # gunicorn
    #- "127.0.0.1:8000:8000"
    #- "127.0.0.1:8001:8001"
    - "0.0.0.0:6000:6000"
    - "0.0.0.0:8585:8585"
    - "0.0.0.0:8000:8000"

    #restart: unless-stopped

    volumes:
      - ./:/opt/

    #depends_on:
    #  - redis
    #  - rqworker


  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: qlines_mongo_container
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
